library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -fno-warn-orphans
    - -fwarn-unused-imports
    - -fwarn-unused-binds
    - -isrc
    - -Widentities
  default-extensions:
    - OverloadedStrings
    - DeriveGeneric
    - DuplicateRecordFields
    - LambdaCase
    - FlexibleContexts
    - FlexibleInstances
tests:
  notion-api-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - notion-api
copyright: 2019 Yannick
maintainer: https://www.dev-log.me
dependencies:
  - safe
  - mtl
  - exceptions
  - aeson-pretty
  - either
  - parsec
  - transformers
  - random
  - containers
  - text
  - uuid
  - unordered-containers
  - bytestring
  - http-client
  - time
  - lens
  - lens-aeson
  - aeson
  - filepath
  - extra
  - split
  - mtl
  - wreq
  - optparse-applicative
  - hspec
  - base >= 4.7 && < 5
name: notion-api
version: 0.0.1
extra-source-files:
  - README.md
  - ChangeLog.md
author: Yannick
github: yannick-cw/notion-api
license: BSD3
description: Please see the README on GitHub at <https://github.com/githubuser/notion-api#readme>
